// Common API Models for dropdown data
class CommonGetAutoRequest {
  final int commandType;
  final int? role;
  final int? id;
  final int? countryId;
  final int? employeeId;
  final int? bizUnit;
  final int? userId;
  final String? date;
  final int? customer;
  final int? customerId;
  final int? distributerId;
  final String? searchText;
  final int? item;
  final int? pageType;

  CommonGetAutoRequest({
    required this.commandType,
    this.role,
    this.id,
    this.countryId,
    this.employeeId,
    this.bizUnit,
    this.userId,
    this.date,
    this.customer,
    this.customerId,
    this.distributerId,
    this.searchText,
    this.item,
    this.pageType,
  });

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {
      'CommandType': commandType,
    };

    if (role != null) data['Role'] = role;
    if (id != null) data['Id'] = id;
    if (countryId != null) data['CountryId'] = countryId;
    if (employeeId != null) data['EmployeeId'] = employeeId;
    if (bizUnit != null) data['BizUnit'] = bizUnit;
    if (userId != null) data['UserId'] = userId;
    if (date != null) data['Date'] = date;
    if (customer != null) data['Customer'] = customer;
    if (customerId != null) data['CustomerId'] = customerId;
    if (distributerId != null) data['DistributerId'] = distributerId;
    if (searchText != null) data['SearchText'] = searchText;
    if (item != null) data['Item'] = item;
    if (pageType != null) data['PageType'] = pageType;

    return data;
  }
}

/// Request model for Tour Plan Products to Discuss (CommandType: 335)
class TourPlanProductsRequest {
  final int userId;
  final int? isFromAMCUser;

  TourPlanProductsRequest({required this.userId, this.isFromAMCUser});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 335,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': isFromAMCUser,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for DCR Products to Discuss (CommandType: 335)
/// Only UserId is dynamic, IsFromAMCUser is always 0
class DcrProductsRequest {
  final int userId;

  DcrProductsRequest({required this.userId});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 335,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': 0,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Mapped Instruments (CommandType: 335)
/// UserId is dynamic, IsFromAMCUser is always 1, CustomerSelectedList contains selected customer
class MappedInstrumentsRequest {
  final int userId;
  final int customerId;

  MappedInstrumentsRequest({required this.userId, required this.customerId});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 335,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': 1,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': [
        {
          'CustomerId': customerId,
        }
      ],
    };
  }
}

/// Request model for Customer Type (CommandType: 230)
class CustomerTypeRequest {
  final int userId;
  final String type;

  CustomerTypeRequest({required this.userId, this.type = 'Service Engineer'});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 230,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': type,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Store List (CommandType: 127, SpecialCondition: "SC")
class StoreListRequest {
  StoreListRequest();

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': null,
      'CommandType': 127,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': '',
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': 'SC',
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Issue To List (CommandType: 150)
class IssueToListRequest {
  final int userId;
  final int bizUnit;

  IssueToListRequest({required this.userId, required this.bizUnit});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 150,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': bizUnit,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Issue Against List (CommandType: 102, Type: "Stock Transfer", SpecialCondition: "Customer")
class IssueAgainstListRequest {
  IssueAgainstListRequest();

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': null,
      'CommandType': 102,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': 'Stock Transfer',
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': 'Customer',
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Division/Category List (CommandType: 215)
class DivisionCategoryRequest {
  DivisionCategoryRequest();

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': null,
      'CommandType': 215,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Item Description List (CommandType: 105)
/// Can use either DivisionId or DistributerId
class ItemDescriptionRequest {
  final int? divisionId;
  final int? distributerId;
  final String? searchText;

  ItemDescriptionRequest({
    this.divisionId,
    this.distributerId,
    this.searchText,
  });

  Map<String, dynamic> toJson() {
    return {
      'SearchText': searchText ?? '%',
      'Id': null,
      'TransactionId': null,
      'UserId': null,
      'CommandType': 105,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': distributerId,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': divisionId,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Batch No List (CommandType: 332)
/// Requires Item ID from selected Item Description
class BatchNoRequest {
  final int itemId;
  final int employeeId;
  final String toDate; // Format: "yyyy-MM-dd"
  final int bizUnit;
  final int module; // 6 for Customer Issue
  final int customerId;
  final int transactionType; // 14 for Customer Issue

  BatchNoRequest({
    required this.itemId,
    required this.employeeId,
    required this.toDate,
    required this.bizUnit,
    this.module = 6,
    required this.customerId,
    this.transactionType = 14,
  });

  Map<String, dynamic> toJson() {
    // Updated to match the new GetAutoBigInt endpoint payload structure
    return {
      'Id': itemId,
      'CommandType': 332,
      'TaxFlag': 0,
      'EmployeeId': employeeId,
      'IncludeCancelled': false,
      'ToDate': toDate,
      'BizUnit': bizUnit,
      'Sector': 0,
      'Module': module,
      'CustomerId': customerId,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'TransactionType': transactionType,
    };
  }
}

/// Request model for Purpose of Visit (CommandType: 337)
class PurposeOfVisitRequest {
  final int userId;
  final String text; // "ServiceEng PurposeVisit" or "Salesrep PurposeVisit"

  PurposeOfVisitRequest({required this.userId, required this.text});

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': null,
      'TransactionId': null,
      'UserId': userId,
      'CommandType': 337,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': text,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Customer List (CommandType: 71)
class CustomerListRequest {
  final int bizUnit;
  final int? customerId;
  final String? searchText;
  final int? userId;
  final int? distributerId;
  final int? customer;
  final int sector;
  final int taxFlag;
  final bool includeCancelled;
  final int? id;
  final int? transactionId;
  final int? countryId;
  final int? clusterId;
  final int? employeeId;
  final String? pageUrl;
  final int? sbuId;
  final int? cityId;
  final int? stateId;
  final int? districtId;
  final int? townId;
  final int? module;

  CustomerListRequest({
    required this.bizUnit,
    this.customerId,
    this.searchText,
    this.userId,
    this.distributerId,
    this.customer,
    this.sector = 0,
    this.taxFlag = 0,
    this.includeCancelled = false,
    this.id,
    this.transactionId,
    this.countryId,
    this.clusterId,
    this.employeeId,
    this.pageUrl,
    this.sbuId,
    this.cityId,
    this.stateId,
    this.districtId,
    this.townId,
    this.module,
  });

  Map<String, dynamic> toJson() {
    return {
      'SearchText': searchText,
      'Id': id,
      'TransactionId': transactionId,
      'UserId': userId,
      'CommandType': 71,
      'CommandText': null,
      'Value': null,
      'CountryId': countryId,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': taxFlag,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': clusterId,
      'EmployeeId': employeeId,
      'PageUrl': pageUrl,
      'IncludeCancelled': includeCancelled,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': sbuId,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': cityId,
      'StateId': stateId,
      'DistributerId': distributerId,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': districtId,
      'TownId': townId,
      'BizUnit': bizUnit,
      'ProcessId': null,
      'FieldName': null,
      'Sector': sector,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': module,
      'Flag': null,
      'CustomerId': customerId,
      'Customer': customer,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

/// Request model for Reporting Manager List (CommandType: 333, Id: 91)
class ReportingManagerRequest {
  ReportingManagerRequest();

  Map<String, dynamic> toJson() {
    return {
      'SearchText': null,
      'Id': 91,
      'TransactionId': null,
      'UserId': null,
      'CommandType': 333,
      'CommandText': null,
      'Value': null,
      'CountryId': null,
      'Key': null,
      'Text': null,
      'Type': null,
      'TaxFlag': 0,
      'SubType': null,
      'RoleMapList': null,
      'CategoryId': null,
      'ClusterId': null,
      'EmployeeId': null,
      'PageUrl': null,
      'IncludeCancelled': false,
      'Program': null,
      'Category': null,
      'Status': null,
      'FromDate': null,
      'ToDate': null,
      'ReportName': null,
      'IsOrganizationUser': null,
      'ItemGroupName': null,
      'Active': null,
      'ConstantMasterPk': null,
      'ConstantMasterActive': null,
      'ConstantMasterGroup': null,
      'ConstantMasterGroupValue': null,
      'ConstantMasterGroupTypeValue': null,
      'TypeValue': null,
      'SbuId': null,
      'LsmLine': null,
      'LsmListType': null,
      'LineId': null,
      'Item': null,
      'Date': null,
      'Department': null,
      'ItemGrade': null,
      'Process': null,
      'Surface': null,
      'Colour': null,
      'Thickness': null,
      'Sterile': null,
      'Nature': null,
      'Grade': null,
      'Length': null,
      'Chlorination': null,
      'Size': null,
      'AdditionalSpec1': null,
      'ProductGroupId': null,
      'SpecialCondition': null,
      'P_COA_SUB_TYPE': null,
      'Group': null,
      'GroupType': null,
      'Name': null,
      'CityId': null,
      'StateId': null,
      'DistributerId': null,
      'TaxCategory': null,
      'OnlyParent': null,
      'DesignationCode': null,
      'DistrictId': null,
      'TownId': null,
      'BizUnit': null,
      'ProcessId': null,
      'FieldName': null,
      'Sector': 0,
      'ConstantMasterParent': null,
      'Vendor': null,
      'ReceiveType': null,
      'Module': null,
      'Flag': null,
      'CustomerId': null,
      'Customer': null,
      'DespatchNo': null,
      'SurveyType': null,
      'PageName': null,
      'Mode': null,
      'Division': null,
      'DivisionGroup': null,
      'Role': null,
      'TypeId': null,
      'PageType': null,
      'IsTax': null,
      'CategoryAccountType': null,
      'AddressLine1': null,
      'AddressLine2': null,
      'AddressLine3': null,
      'PostalCode': null,
      'VehicleNo': null,
      'StatusType': null,
      'CurrentStatusID': null,
      'ProcessType': null,
      'IsMaterialIssue': false,
      'IsItemIssue': false,
      'ReferenceType': null,
      'TransactionType': null,
      'ManufacturerMasterDoc': null,
      'BrandName': null,
      'AccountSubType': null,
      'IsFromAMCUser': null,
      'IsContra': null,
      'receiveSubType': null,
      'IssueId': null,
      'CustomerSelectedList': null,
    };
  }
}

class CommonDropdownItem {
  final int id;
  final String text;
  final int doubleTank;
  final int virtual;
  final int version;
  final String compoundStartDate;
  final String compoundEndDate;
  final String name;
  final int stock;
  final String address;
  final int uom;
  final int hasChild;
  final int hasInstrument;
  final int category;
  final String employeeName;
  final String accountNo;
  final String branch;
  final String manufacturerName;
  final String manufacturerCountry;
  final int account;
  final int pageType;
  final String no;
  final int value;
  final String expiryDate;
  final int accountSubType;
  final int totalAmount;
  final int balanceAmount;
  final String cityName;
  final double rate;
  final String typeText;
  final int currency;
  final int type;
  final int days;
  final String invoiceNo;
  final int invoiceId;
  final int saleInvoiceDetailId;
  final int level;
  final int divisionGroupId;
  final String currencyText;
  final String decimalFormat;
  final String rateFormat;
  final String code;
  final String addressLine1;
  final String addressLine2;
  final String addressLine3;
  final String postalCode;
  final int countryId;
  final int stateId;
  final int cityId;
  final String packSize;
  final String hsCode;
  final String taxNumber;
  final int role;
  final String customer;
  final String planDate;
  final String designation;
  final String stateText;
  final int clusterId;
  final int subType;
  final int isReceiptBatchRequired;
  final int displayOrder;

  CommonDropdownItem({
    required this.id,
    required this.text,
    required this.doubleTank,
    required this.virtual,
    required this.version,
    required this.compoundStartDate,
    required this.compoundEndDate,
    required this.name,
    required this.stock,
    required this.address,
    required this.uom,
    required this.hasChild,
    required this.hasInstrument,
    required this.category,
    required this.employeeName,
    required this.accountNo,
    required this.branch,
    required this.manufacturerName,
    required this.manufacturerCountry,
    required this.account,
    required this.pageType,
    required this.no,
    required this.value,
    required this.expiryDate,
    required this.accountSubType,
    required this.totalAmount,
    required this.balanceAmount,
    required this.cityName,
    required this.rate,
    required this.typeText,
    required this.currency,
    required this.type,
    required this.days,
    required this.invoiceNo,
    required this.invoiceId,
    required this.saleInvoiceDetailId,
    required this.level,
    required this.divisionGroupId,
    required this.currencyText,
    required this.decimalFormat,
    required this.rateFormat,
    required this.code,
    required this.addressLine1,
    required this.addressLine2,
    required this.addressLine3,
    required this.postalCode,
    required this.countryId,
    required this.stateId,
    required this.cityId,
    required this.packSize,
    required this.hsCode,
    required this.taxNumber,
    required this.role,
    required this.customer,
    required this.planDate,
    required this.designation,
    required this.stateText,
    required this.clusterId,
    required this.subType,
    required this.isReceiptBatchRequired,
    required this.displayOrder,
  });

  factory CommonDropdownItem.fromJson(Map<String, dynamic> json) {
    return CommonDropdownItem(
      id: json['id'] ?? 0,
      text: json['text'] ?? '',
      doubleTank: json['doubleTank'] ?? 0,
      virtual: json['virtual'] ?? 0,
      version: json['version'] ?? 0,
      compoundStartDate: json['compoundStartDate'] ?? '',
      compoundEndDate: json['compoundEndDate'] ?? '',
      name: json['name'] ?? '',
      stock: json['stock'] ??
          json['quantityInStock'] ??
          0, // Support both 'stock' and 'quantityInStock'
      address: json['address'] ?? '',
      uom: json['uom'] ?? 0,
      hasChild: json['hasChild'] ?? 0,
      hasInstrument: json['hasInstrument'] ?? 0,
      category: json['category'] ?? 0,
      employeeName: json['employeeName'] ?? '',
      accountNo: json['accountNo'] ?? '',
      branch: json['branch'] ?? '',
      manufacturerName: json['manufacturerName'] ?? '',
      manufacturerCountry: json['manufacturerCountry'] ?? '',
      account: json['account'] ?? 0,
      pageType: json['pageType'] ?? 0,
      no: json['no'] ?? '',
      value: json['value'] ?? 0,
      expiryDate: json['expiryDate'] ?? '',
      accountSubType: json['accountSubType'] ?? 0,
      totalAmount: json['totalAmount'] ?? 0,
      balanceAmount: json['balanceAmount'] ?? 0,
      cityName: json['cityName'] ?? '',
      rate: json['rate'] != null
          ? (json['rate'] is int
              ? json['rate'].toDouble()
              : (json['rate'] as num).toDouble())
          : 0.0,
      typeText: json['typeText'] ?? '',
      currency: json['currency'] ?? 0,
      type: json['type'] ?? 0,
      days: json['days'] ?? 0,
      invoiceNo: json['invoiceNo'] ?? '',
      invoiceId: json['invoiceId'] ?? 0,
      saleInvoiceDetailId: json['saleInvoiceDetailId'] ?? 0,
      level: json['level'] ?? 0,
      divisionGroupId: json['divisionGroupId'] ?? 0,
      currencyText: json['currencyText'] ?? '',
      decimalFormat: json['decimalFormat'] ?? '',
      rateFormat: json['rateFormat'] ?? '',
      code: json['code'] ?? '',
      addressLine1: json['addressLine1'] ?? '',
      addressLine2: json['addressLine2'] ?? '',
      addressLine3: json['addressLine3'] ?? '',
      postalCode: json['postalCode'] ?? '',
      countryId: json['countryId'] ?? 0,
      stateId: json['stateId'] ?? 0,
      cityId: json['cityId'] ?? 0,
      packSize: json['packSize'] ?? '',
      hsCode: json['hsCode'] ?? '',
      taxNumber: json['taxNumber'] ?? '',
      role: json['role'] ?? 0,
      customer: json['customer'] ?? '',
      planDate: json['planDate'] ?? '',
      designation: json['designation'] ?? '',
      stateText: json['stateText'] ?? '',
      clusterId: json['clusterId'] ?? 0,
      subType: json['subType'] ?? 0,
      isReceiptBatchRequired: json['isReceiptBatchRequired'] ?? 0,
      displayOrder: json['displayOrder'] ?? 0,
    );
  }
}

/// Tax Component Request Model
class TaxComponentRequest {
  final int id;
  final int? userId;
  final int pageNumber;
  final int pageSize;
  final String? searchText;
  final int sortOrder;
  final int sortDir;
  final String? sortField;
  final String? json;
  final String? filterExpression;
  final int? pageId;
  final int? type;

  TaxComponentRequest({
    required this.id,
    this.userId,
    this.pageNumber = 0,
    this.pageSize = 0,
    this.searchText,
    this.sortOrder = 0,
    this.sortDir = 0,
    this.sortField,
    this.json,
    this.filterExpression,
    this.pageId,
    this.type,
  });

  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'UserId': userId,
      'PageNumber': pageNumber,
      'PageSize': pageSize,
      'SearchText': searchText,
      'SortOrder': sortOrder,
      'SortDir': sortDir,
      'SortField': sortField,
      'Json': json,
      'FilterExpression': filterExpression,
      'PageId': pageId,
      'Type': type,
    };
  }
}

/// Tax Component Response Model
class TaxComponentResponse {
  final int id;
  final int chargesType; // 1=SubTotal, 2=Discount, 3=OtherCharge, 4=Tax, 5=PriceAdjustment, 6=GrandTotal, 7=ShippingCharge, 8=DedAdvPaid
  final String? formula;
  final String? label;
  final int? displayOrder;
  final bool? isActive;
  final String? description;

  TaxComponentResponse({
    required this.id,
    required this.chargesType,
    this.formula,
    this.label,
    this.displayOrder,
    this.isActive,
    this.description,
  });

  factory TaxComponentResponse.fromJson(Map<String, dynamic> json) {
    return TaxComponentResponse(
      id: json['id'] ?? 0,
      chargesType: json['chargesType'] ?? json['ChargesType'] ?? 0,
      formula: json['formula'] ?? json['Formula'],
      label: json['label'] ?? json['Label'],
      displayOrder: json['displayOrder'] ?? json['DisplayOrder'],
      isActive: json['isActive'] ?? json['IsActive'],
      description: json['description'] ?? json['Description'],
    );
  }
}

/// ChargesType Enum Helper
enum ChargesType {
  subTotal(1),
  discount(2),
  otherCharge(3),
  tax(4),
  priceAdjustment(5),
  grandTotal(6),
  shippingCharge(7),
  dedAdvPaid(8);

  final int value;
  const ChargesType(this.value);

  static ChargesType? fromInt(int? value) {
    if (value == null) return null;
    return ChargesType.values.firstWhere(
      (e) => e.value == value,
      orElse: () => ChargesType.subTotal,
    );
  }
}
